language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libsdl2-dev libfreetype6-dev

before_script:
     - mkdir build
     - cd build
     - cmake ..

script: make
